#!/usr/bin/env bash

# Name: BHARATH KRISHNA
# ID: 25182359
# Date of completion:

# How to run this script: ./analyse trending_videos_clean.csv

# Summary:
# Performs data analysis operations on the provided CSV file.

# Check if exactly one argument is passed
if [[ $# -ne 1 ]]
then
    echo "ERROR: $0 expects exactly one argument"
    exit 1
fi

file=$1

# Check whether the input file is a CSV file
if [[ "$file" != *.csv ]]
then
    echo "ERROR: Input file expected in a CSV format"
    exit 1
fi

# Check if the file exists, is readable and is not empty
if [[ ! -f "$file" || ! -r "$file" || ! -s "$file" ]]
then
        echo "ERROR: The specified input file $file does not exist, is not readable or is empty"
        exit 1
fi