name: Tests

on:
  push:
  pull_request:

jobs:
  test-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod u+x clean analyse tests/test_clean tests/test_analyse

      - name: Run tests clean
        run: bash tests/test_clean

  test-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod u+x clean analyse tests/test_clean tests/test_analyse

      - name: Run tests analyse
        run: bash tests/test_analyse
